import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import { Providers } from "./providers";
import "./globals.css";

export const metadata = {
  title: "PenOrbit",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}